# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "feature/practice-pr" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install git
      run: sudo apt-get update && sudo apt-get install -y git 
    
    - name: clone repo
      run: |
        git clone https://github.com/${{ github.repository }} .
        git checkout ${{ github.head_ref }}

    - name: Install Python
      run: |
        sudo apt-get install -y python3 python3-pip
        python3 --version

    - name: Install dependencies
      run: pip3 install flake8

    - name: Lint code
      run: flake8 app1.py app2.py app3.py app4.py